config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = "localhost:3000"
  
  resources :statuses

  resources :books do
    resources :book_statuses, except: [:index, :show]
    resources :reviews
  end

  resources :book_statuses, only: :index
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  # resources :users # must be after devise routes declaration
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /statuses or /statuses.json
  def index
    authorize Status
    @statuses = Status.all
  end

  # GET /statuses/1 or /statuses/1.json
  def show
    authorize @status
  end

  # GET /statuses/new
  def new
    @status = Status.new
    authorize @status
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses or /statuses.json
  def create
    @status = Status.new(status_params)

    authorize @status

    respond_to do |format|
      if @status.save
        format.html { redirect_to status_url(@status), notice: "Status was successfully created." }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1 or /statuses/1.json
  def update
    authorize @status

    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to status_url(@status), notice: "Status was successfully updated." }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1 or /statuses/1.json
  def destroy
    authorize @status
    
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url, notice: "Status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:title)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_with(model: status, class: "contents") do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
        <% status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary w-full" %>
  </div>
<% end %>

app/views/statuses/_status.html.erb
<div id="<%= dom_id status %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= status.title %>
  </p>

  <% if action_name != "show" %>
    <div class="flex flex-row gap-2">
      <%= link_to "Show this status", status, class: "btn btn-primary" %>
      <%= link_to 'Edit this status', edit_status_path(status), class: "btn btn-primary" %>
      <%= button_to 'Destroy this status', status_path(status), method: :delete, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/statuses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="text-4xl">Editing status</h1>

  <%= render "form", status: @status %>

  <div class="flex flex-row gap-3 w-full">
    <%= link_to "Show this status", @status, class: "btn btn-primary w-full" %>
    <%= link_to "Back to statuses", statuses_path, class: "btn btn-primary w-full" %>
  </div>
</div>

app/views/statuses/index.html.erb
<div class="w-full">

  <div class="flex justify-between items-center">
    <h1 class="text-4xl">Statuses</h1>
    <%= link_to 'New status', new_status_path, class: "btn btn-primary" %>
  </div>

  <div id="statuses" class="min-w-full">
    <%= render @statuses %>
  </div>
</div>

app/views/statuses/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="text-4xl">New status</h1>

  <%= render "form", status: @status %>

  <%= link_to 'Back to statuses', statuses_path, class: "btn btn-primary w-full" %>
</div>

app/views/statuses/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @status %>

    <div class="flex flex-row gap-2">
      <%= link_to 'Back to statuses', statuses_path, class: "btn btn-primary" %>
      <%= link_to 'Edit this status', edit_status_path(@status), class: "btn btn-primary" %>
      <%= button_to 'Destroy this status', status_path(@status), method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
</div>