config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = "localhost:3000"
  
  resources :statuses

  resources :books do
    resources :book_statuses, except: [:index, :show]
    resources :reviews
  end

  resources :book_statuses, only: :index
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  # resources :users # must be after devise routes declaration
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book.rb
class Book < ApplicationRecord
  after_commit :add_default_cover, on: [:create, :update]

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user

  has_many :book_statuses, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_one_attached :cover

  validates :title, presence: true, length: {:maximum => 150}
  validates :publication_date, presence: true
  validates :chapters, presence: true
  validates :page_count, presence: true
  validates :cover,
    content_type: ['image/png', 'image/jpg', 'image/jpeg'], size: { less_than: 500.kilobytes , message: 'size should be under 500 kilobytes' }
  validates :description, presence: true

  def to_s
    self.title + ' by ' + user.get_full_name
  end

  scope :latest, -> { limit(3).order(created_at: :desc) }
  scope :popular, -> { limit(3).order(book_statuses_count: :desc) }

  private

  def add_default_cover
    unless cover.attached?
      self.cover.attach(io: File.open(Rails.root.join("app", "assets", "images", "default_cover.jpg")), filename: 'default_cover.jpg' , content_type: "image/jpg")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit create update destroy ]

  # GET /books or /books.json
  def index
    @q = policy_scope(Book).ransack(params[:q])
    @pagy, @books = pagy(@q.result(distinct: true))
  end

  # GET /books/1 or /books/1.json
  def show
    @author = @book.user
    if user_signed_in?
      @book_status = BookStatus.where(user: current_user, book: @book).first # to show user book_status in book view
    end
    @review = Review.new
    @reviews = @book.reviews.order(created_at: :desc)
  end

  # GET /books/new
  def new
    @book = Book.new
    authorize @book
  end

  # GET /books/1/edit
  def edit
    authorize @book
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    authorize @book
    @book.user = current_user
    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    authorize @book
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    authorize @book
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :publication_date, :chapters, :page_count, :cover, :description)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p class="my-5">
    <h1 class="text-4xl text-center"><%= book.title %></h1>
  </p>

  <p class="my-5 flex justify-center h-96">
    <%= image_tag book.cover.variant(resize_to_limit: [384, 384]) if book.cover.attached? %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Author:</strong>
    <%= book.user.get_full_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= book.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Publication date:</strong>
    <%= book.publication_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Chapters:</strong>
    <%= book.chapters %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Page count:</strong>
    <%= book.page_count %>
  </p>

  <% if action_name != "show" && policy(book).update? %>
    <%= link_to "Show this book", book, class: "btn btn-secondary" %>
    <%= link_to 'Edit this book', edit_book_path(book), class: "btn btn-primary" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/books/_bookCard.html.erb
<div class="bg-white p-4 rounded-xl shadow-md hover:shadow-2xl cursor-pointer hover:scale-110 transition-all">
    <%= link_to book_path(book) do %>
        <h3 class="text-xl text-center p-1">
            <%= book %>
        </h3>
        <div class="flex justify-center p-1 h-52">
            <%= image_tag book.cover if book.cover.attached? %>
        </div>
        <p class="text-sm p-1">
            <%= book.description.truncate(50) %>
        </p>
        <p class="text-xs font-bold p-1">
            Publication date: <%= book.publication_date %>
        </p>
        <% if user_signed_in? && policy(book).update? %>
            <div class="flex flex-row gap-2 p-1">
                <%= link_to "Edit", edit_book_path(book), class: "btn btn-primary" %>
                <%= button_to "Delete", book_path(book), method: :delete, class: "btn btn-danger" %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/books/_bookRow.html.erb
<div class="bg-indigo-400 hover:bg-indigo-500 text-white rounded shadow w-full h-20 px-4 py-2 my-3 shadow-md hover:shadow-2xl cursor-pointer hover:scale-110 transition-all">
    <%= link_to book_path(book), class: "block w-full h-full flex flex-row items-center" do %>
        <div class="mr-6">
            <%= image_tag book.cover.variant(resize_to_limit: [65, 65]) if book.cover.attached? %>
        </div>
        <p class="mr-auto">
            <%= book %>
        </p>
        <p>
            Publication date: <%= book.publication_date %>
        </p>
        <% if user_signed_in? && policy(book).update? %>
            <div class="flex flex-row gap-2 p-1">
                <%= link_to "Edit", edit_book_path(book), class: "btn btn-primary" %>
                <%= button_to "Delete", book_path(book), method: :delete, class: "btn btn-danger" %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book, class: "contents") do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :publication_date %>
    <%= form.date_field :publication_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :chapters %>
    <%= form.number_field :chapters, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :page_count %>
    <%= form.number_field :page_count, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :cover %>
    <%= form.file_field :cover, class: "form-control", id: "cover-input" %>
    <div id="cover-previewer"></div>
    <%= image_tag book.cover.variant(resize_to_limit: [200, 200]) if book.cover.attached? %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "form-control h-20" %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary w-full" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="text-4xl">Editing book (<%= @book.title %>)</h1>

  <%= render "form", book: @book %>

  <div class="flex flex-row gap-4">
    <%= link_to "Show this book", @book, class: "btn btn-secondary w-full" %>
    <%= link_to "Back to books", books_path, class: "btn btn-secondary w-full" %>
  </div>
</div>

app/views/books/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="text-4xl">Books</h1>
    <% if user_signed_in? && policy(Book).create? %>
      <%= link_to 'New book', new_book_path, class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="grid grid-cols-4 gap-2">
    <div class="col-span-1">
      <%= search_form_for @q do |f| %>

        <div class="form-group">
          <%= f.label :title_cont %>
          <%= f.search_field :title_cont, placeholder: "Title", class: "form-control" %>
        </div>


        <%= f.label :publication_date %>
        <div class="grid grid-cols-2 gap-1">
          <div class="form-group">
            <%= f.date_field :publication_date_gteq, placeholder: "Start", class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.date_field :publication_date_lteq, placeholder: "End", class: "form-control" %>
          </div>
        </div>

        <%= f.label :chapters %>
        <div class="grid grid-cols-2 gap-1">
          <div class="form-group">
            <%= f.number_field :chapters_gteq, placeholder: "min", class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.number_field :chapters_lteq, placeholder: "max", class: "form-control" %>
          </div>
        </div>

        <%= f.label :page_count %>
        <div class="grid grid-cols-2 gap-1">
          <div class="form-group">
            <%= f.number_field :page_count_gteq, placeholder: "min", class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.number_field :page_count_lteq, placeholder: "max", class: "form-control" %>
          </div>
        </div>

        <%= f.submit class: "btn btn-primary w-full" %>
      <% end %>
    </div>
    <div id="books" class="col-span-3">
      Sort by:
      <div class="flex flex-row gap-2">
        <%= sort_link(@q, :title, class: "btn btn-primary") %>
        <%= sort_link(@q, :publication_date, class: "btn btn-primary") %>
        <%= sort_link(@q, :chapters, class: "btn btn-primary") %>
        <%= sort_link(@q, :page_count, class: "btn btn-primary") %>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 flex-wrap">
        <% @books.each do |book| %>
          <%= render "books/bookCard", book: book %>
        <% end %>
      </div>
      <div class="p-4">
        <%== pagy_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="text-4xl">New book</h1>

  <%= render "form", book: @book %>

  <%= link_to 'Back to books', books_path, class: "btn btn-secondary w-full" %>
</div>

app/views/books/show.html.erb
<%= render @book %>

<div class="flex flex-row gap-4">
  <% if user_signed_in? %>
    <% if @book_status %>
      <% if policy(@book_status).update? %>
        <%= link_to edit_book_book_status_path(@book, @book_status), class: "btn btn-primary" do %>
          Edit book status (<%= @book_status.status %>)<% if @book_status.status.title == "reading" %> (<%= @book.page_count %> / <%= @book_status.pages %>)<% end %>
        <% end %>
      <% end %>
    <% else %>
      <% if policy(BookStatus).create? %>
        <%= link_to 'Add to my library', new_book_book_status_path(@book), class: "btn btn-primary" %>
      <% end %>
    <% end %>

    <% if current_user.has_role?(:admin) || (current_user.has_role?(:author) && @book.user_id == current_user.id) %>
      <%= link_to 'Edit this book', edit_book_path(@book), class: "btn btn-primary" %>
      <%= button_to 'Destroy this book', book_path(@book), method: :delete, class: "btn btn-danger" %>
    <% end %>
  <% end %>

  <%= link_to 'Back to books', books_path, class: "btn btn-primary" %>

</div>

<h2 class="text-3xl">Reviews (<%= @book.reviews_count || 0 %>)</h2>

<% if user_signed_in? %>
  <%= render "reviews/form" %>
<% end %>

<div class="reviews" data-book-id="<%= @book.id %>"<% if user_signed_in? %> data-user-id="<%= current_user.id %>"<% end %>>
  <% @reviews.each do |review| %>
    <%= render "reviews/review", review: review %>
  <% end %>
</div>