config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = "localhost:3000"
  
  resources :statuses

  resources :books do
    resources :book_statuses, except: [:index, :show]
    resources :reviews
  end

  resources :book_statuses, only: :index
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  # resources :users # must be after devise routes declaration
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/book_statuses_controller.rb
class BookStatusesController < ApplicationController
  before_action :set_book_status, only: %i[ show edit update destroy ]
  before_action :set_book, except: :index
  before_action :authenticate_user!

  # GET /book_statuses or /book_statuses.json
  def index
    authorize BookStatus
    @book_statuses = BookStatus.all
  end

  # GET /book_statuses/1 or /book_statuses/1.json
  def show
  end

  # GET /book_statuses/new
  def new
    @book_status = BookStatus.new

    authorize @book_status
    
    old_book_status = BookStatus.where(user: current_user, book: @book)
    
    if old_book_status.exists?
      redirect_to edit_book_book_status_path(@book, old_book_status.first)
    end
  end

  # GET /book_statuses/1/edit
  def edit
    authorize @book_status
  end

  # POST /book_statuses or /book_statuses.json
  def create
    @book_status = BookStatus.new(book_status_params)

    authorize @book_status

    @book_status.book_id = @book.id
    @book_status.user_id = current_user.id

    respond_to do |format|
      if @book_status.save
        # format.html { redirect_to book_book_status_url(@book, @book_status), notice: "Book status was successfully created." }
        format.html { redirect_to book_url(@book), notice: "Book status was successfully created." }
        format.json { render :show, status: :created, location: @book_status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_statuses/1 or /book_statuses/1.json
  def update
    authorize @book_status
    
    respond_to do |format|
      if @book_status.update(book_status_params)
        # format.html { redirect_to book_book_status_url(@book, @book_status), notice: "Book status was successfully updated." }
        format.html { redirect_to book_url(@book), notice: "Book status was successfully updated." }
        format.json { render :show, status: :ok, location: @book_status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_statuses/1 or /book_statuses/1.json
  def destroy
    authorize @book_status
    
    @book_status.destroy

    respond_to do |format|
      # format.html { redirect_to book_book_statuses_url(@book), notice: "Book status was successfully destroyed." }
      format.html { redirect_to book_url(@book), notice: "Book status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_status
      @book_status = BookStatus.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    # Only allow a list of trusted parameters through.
    def book_status_params
      params.require(:book_status).permit(:status_id, :pages)
    end
end

app/helpers/book_statuses_helper.rb
module BookStatusesHelper
end

app/views/book_statuses/_book_status.html.erb
<div id="<%= dom_id book_status %>">
  <% if action_name != "show" %>
    <%= link_to "Show this book status", book_book_status_path(book_status.book_id, book_status), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this book status', edit_book_book_status_path(book_status.book_id, book_status), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/book_statuses/_form.html.erb
<%= form_with(model: [@book, book_status], class: "contents") do |form| %>
  <% if book_status.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(book_status.errors.count, "error") %> prohibited this book_status from being saved:</h2>

      <ul>
        <% book_status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group my-5">
    <%= form.label :status_id %>
    <%= form.select :status_id, Status.pluck(:title, :id), {}, { class: "form-control", id: "book-status-select" } %>
  </div>
  <div class="form-group my-5" id="book-status-pages"<% if action_name == "new" || book_status.status.title != "reading" %> style="display: none;"<% end %>>
    <%= form.label :pages %><br />
    <%= @book.page_count %> / <%= form.number_field :pages, { min: 1, max: @book.page_count, class: "w-20 form-control" } %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/book_statuses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="text-4xl">Editing book status</h1>

  <%= render "form", book_status: @book_status %>

  <%= button_to "Delete this book status", book_book_status_path(@book, @book_status), method: :delete, class: "btn btn-danger" %>
</div>

app/views/book_statuses/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="text-4xl text-center">Library</h1>

  <div id="book_statuses" class="min-w-full">
    <% Status.all.each do |status| %>
      <div class="my-2">
        <h1 class="text-4xl mb-2"><%= status %></h1>
        
        <div class="ml-5">
          <% BookStatus.where(user: current_user, status: status).each do |book_status| %>
            <%= render "books/bookRow", book: book_status.book %>
          <% end.empty? and begin %>
            <h2 class="text-3xl mb-2">
              No Books
            </h2>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/book_statuses/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @book_status %>

    <%= link_to 'Edit this book_status', edit_book_book_status_path(@book, @book_status), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this book_status', book_book_status_path(@book, @book_status), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to book_statuses', book_statuses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>