config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = "localhost:3000"
  
  resources :statuses

  resources :books do
    resources :book_statuses, except: [:index, :show]
    resources :reviews
  end

  resources :book_statuses, only: :index
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  # resources :users # must be after devise routes declaration
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_footer.html.erb
<footer class="md:flex lg:flex md:felx-row lg:flex-row text-white min-h-80 px-10 py-6 bg-stone-700">
    <div class="w-96 sm:mr-0 md:mr-96 lg:mr-96 mb-10">
        <h2 class="text-3xl py-3">
            Rails-Books
        </h2>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
            molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
            numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
            optio, eaque rerum! Provident similique accusantium nemo autem.
        </p>
    </div>
    <div class="w-60 mb-10">
        <h2 class="text-3xl py-3">
            Contact us
        </h2>
        <ul>
            <li><a href="tel:01000000000" class="link">Call us now</a></li>
            <li><a href="https://facebook.com" class="link">Facebook</a></li>
            <li><a href="https://twitter.com" class="link">Twitter</a></li>
            <li><a href="https://Instagram.com" class="link">Instagram</a></li>
            <li>&#169; 2020 <a href="https://github.com/HazemLenin" class="link underline">Hazem Lenin</a>. All rights reserved.</li>
        </ul>
    </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="flex justify-between text-white p-6 bg-stone-700">
    <ul class="flex flex-row align-items items-center gap-3">
        <li class="nav-item">
            <%= link_to "Rails Books", root_path, class: "#{'text-stone-300' if current_page?(root_path)}" %>
        </li>
        <% if user_signed_in? %>
            <% if current_user.has_role?(:reader) %>
                <li class="nav-item dropdown-btn<% if current_page?(books_path) || current_page?(book_statuses_path) %> text-stone-300<% end %>">
                    Reader
                    <ul class="dropdown">
                        <li class="dropdown-item">
                            <%= link_to "Books", books_path, class: "#{'text-black' if current_page?(books_path)}" %>
                        </li>
                        <li class="dropdown-item">
                            <%= link_to "Library", book_statuses_path, class: "#{'text-black' if current_page?(book_statuses_path)}" %>
                        </li>
                    </ul>
                </li>
            <% end %>
            <% if current_user.has_role?(:author) %>
                <li class="nav-item dropdown-btn<% if current_page?(books_path) %> text-stone-300<% end %>">
                    Author
                    <ul class="dropdown">
                        <li class="dropdown-item">
                            <%= link_to "My Books", books_path, class: "#{'text-black' if current_page?(books_path)}" %>
                        </li>
                    </ul>
                </li>
            <% end %>
            <% if current_user.has_role?(:admin) %>
                <li class="nav-item dropdown-btn<% if current_page?(books_path) || current_page?(rails_admin_path) %> text-stone-300<% end %>">
                    Admin
                    <ul class="dropdown">
                        <li class="dropdown-item">
                            <%= link_to "Books", books_path, class: "#{'text-black' if current_page?(books_path)}" %>
                        </li>
                        <li class="dropdown-item">
                            <%= link_to "Statuses", statuses_path, class: "#{'text-black' if current_page?(statuses_path)}" %>
                        </li>
                        <li class="dropdown-item">
                            <%= link_to "Dashboard", rails_admin_path, class: "#{'text-black' if current_page?(rails_admin_path)}" %>
                        </li>
                    </ul>
                </li>
                
            <% end %>
        <% else %>
            <li class="nav-item">
                <%= link_to "Books", books_path, class: "#{'text-stone-300' if current_page?(books_path)}" %>
            </li>
        <% end %>
    </ul>
    <ul class="flex flex-row align-items items-center gap-3">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to current_user.username, edit_user_registration_path, class: "#{'text-stone-300' if current_page?(edit_user_registration_path)}" %>
            </li>
            <li class="nav-item">
                <%= button_to "Logout", destroy_user_session_path, class: "#{'text-stone-300' if current_page?(destroy_user_session_path)}", method: :delete %>
            </li>
        <% else %>            
            <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "#{'text-stone-300' if current_page?(new_user_session_path)}" %>
            </li>
            <li class="nav-item">
                <%= link_to "Signup", new_user_registration_path, class: "#{'text-stone-300' if current_page?(new_user_registration_path)}" %>
            </li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <%= action_cable_meta_tag %>
  </head>

  <body class="bg-slate-200">
    <%= render "layouts/nav" %>

    <% flash.each do |type, msg| %>
      <% if type == "notice" %>
        <div class="bg-teal-100 border-2 border-teal-500 text-teal-900 p-4"><%= msg %></div>
      <% elsif type == "alert" %> 
        <div class="bg-red-100 border-2 border-red-400 text-red-500 p-4"><%= msg %></div>
      <% else %>
        <div class="p-4"><%= msg %></div>
      <% end %>
    <% end %>

    <main class="container px-5 md:px-40 lg:px-40 mx-auto my-6 min-h-screen">
      <%= yield %>
    </main>
    
    <%= render "layouts/footer" %>
  </body>
</html>